const EVENTS = {
  connection: "connection",
  CLIENT: {
    CREATE_ROOM: "CREATE_ROOM",
    SEND_ROOM_MESSAGE: "SEND_ROOM_MESSAGE",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    COMPOSE_ROOM_MESSAGE: "COMPOSE_ROOM_MESSAGE",
    ROOM_HIDE: "ROOM_HIDE"
  },
  SERVER: {
    ROOMS: "ROOMS",
    JOINED_ROOM: "JOINED_ROOM",
    ROOM_MESSAGE: "ROOM_MESSAGE",
    LEFT_ROOM: "LEFT_ROOM",
    COMPOSED_ROOM_MESSAGE: "COMPOSED_ROOM_MESSAGE",
    ROOM_HIDDEN: "ROOM_HIDDEN"
  },
};

export default EVENTS;
